### ISSUE TITLE
Chocolat ou algues ? 

### ISSUE THREAD

**Issue by knilfo** [Seshat-Ya/Projet-BigBang#2]
J'ouvre le débat : chocolat ou algues ?

**Comment by YasmineSn** [comment]
Chocolat à l'algue ! avec une pincée de gingembre 
Non ?

**Comment by YasmineSn** [comment]
en fait il n'y a pas lieu d'avoir un débat, c'est algues tout court, 
je ferme l'issue

**Comment by YasmineSn** [comment]
c'était évidemment un test, je vais laisser un commentaire pour voir ce qui se passe

**Comment by YasmineSn** [comment]
le dossier est fermé mais je peux continuer à écrire. Est-ce que tu es notifié ?

**Comment by knilfo** [comment]
Oui je suis notifié. Je vais tenter de répondre au mail de notif pour voir si tu le reçois. Si on peut juste envoyer des mails et qu'ils soient stockés en comment tout seul, c'est pas mal :)

--
Keyvan  Nilforoushan
+336 64 69 30 02

**Comment by knilfo** [comment]
Ah oui cela fonctionne

**Comment by YasmineSn** [comment]
génial ça fonctionne sur l'issue, et ça en crée un autre

**Comment by YasmineSn** [comment]
très sympa
